######################################################################
# @author      : newos (newos@$HOSTNAME)
# @file        : Makefile
# @created     : Sunday Jul 14, 2024 12:23:56 CEST
######################################################################

CC= c++


NAME: 
	$(CC)  remove.cpp -o remove
	$(CC)  print.cpp -o print
	$(CC)  upload.cpp -o upload

